services:
  postgres12_sb:
    image: postgres:12-alpine
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres12_sb:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres12_sb
    # entrypoint: ["/app/wait-for.sh", "postgres12_sb:5432", "--", "/app/start.sh"]
    # command: [ "/app/main" ]

